const PREFIX_UPDATE_LOCATION = 'UPDATE_LOCATION';
const PREFIX_ALERT           = 'ALERT';
const PREFIX_MENU            = 'MENU';
const PREFIX_SETTINGS        = 'SETTINGS';
const PREFIX_NEW_PROFILE     = 'NEW_PROFILE';
const PREFIX_NEW_ARCHIVE     = 'NEW_ARCHIVE';
const PREFIX_OWN_CLOUD       = 'OWN_CLOUD';

module.exports = {
	PREFIX_OWN_CLOUD,
	PREFIX_NEW_ARCHIVE,
	PREFIX_NEW_PROFILE,
	PREFIX_SETTINGS,
	PREFIX_MENU,
	PREFIX_ALERT,
	PREFIX_UPDATE_LOCATION
};

