const PREFIX_UPDATE_LOCATION = 'UPDATE_LOCATION';
const PREFIX_ALERT            = 'ALERT';
const PREFIX_MENU             = 'MENU';
const PREFIX_SETTINGS         = 'SETTINGS';

module.exports = {
	PREFIX_SETTINGS,
	PREFIX_MENU,
	PREFIX_ALERT,
	PREFIX_UPDATE_LOCATION
};
